#!/bin/bash
#Aggressive Block Module

BRed='\033[1;31m' #Bold Red
BGr='\033[1;32m' #Bold Green
NC='\033[0m' #No Color

echo -e "\n[${Bgr}+${NC}] Loading Aggressive Block Module\n"
echo "[$(date)] Aggressive Block  Loaded Successfully" >> wizard.log
echo 
echo -e "[${BGr}+${NC}] Incoming Traffic"
echo -e "\n[${BRed}+${NC}] Packet-type to Reject with\n"
echo -e "[${GR}+${NC}] icmp-net-unreachable"
echo -e "[${GR}+${NC}] icmp-host-unreachable"
echo -e "[${GR}+${NC}] icmp-proto-unreachable"
echo -e "[${GR}+${NC}] icmp-port-unreachable"
echo -e "[${GR}+${NC}] icmp-net-prohibited"
echo -e "[${GR}+${NC}] icmp-host-prohibited"
echo -e "[${GR}+${NC}] tcp-reset"
echo -e "[${GR}+${NC}] icmp-admin-prohibited"

read -p "[*] Please Enter the Relevant Packet-type to Reject with::one only:→ " Reject
echo
echo -e "[${GR}+${NC}] Some Common Services-|-|-Ports"
echo -e "${BRed}→${NC} HTTP::80"
echo -e "${BRed}→${NC} HTTPS::443"
echo -e "${BRed}→${NC} SSH::22"
echo -e "${BRed}→${NC} FTP::21"
echo -e "${BRed}→${NC} Telnet::23"
echo -e "${BRed}→${NC} DNS::53"
echo -e "${BRed}→${NC} SMTP::25"
echo -e "${BRed}→${NC} POP3::110"
echo -e "${BRed}→${NC} NTP::123"
echo -e "${BRed}→${NC} IMAP::143"
echo -e "${BRed}→${NC} SNMP::161"
echo -e "${BRed}→${NC} IRC::194"
echo -e "${BRed}→${NC} NetBIOS::139--UDP"
echo -e "${BRed}→${NC} SMB::445--UDP"

read -p "[*] Enter The Port Numbers To Block::seprate by spaces if needed:[TCP]→ " T_Ports
read -p "[*] Enter The Port Numbers To Block::seprate by spaces if needed:[UDP]→ " U_Ports
echo
read -p "[*] Enter the IP address or Networks(CIDR) to Block:→ " IPs

block() {
	for port in  $T_Ports
	do
		for ip in $IPs
		do
			iptables -A INPUT -p tcp --dport $port -s ${IPs} -j REJECT --reject-with ${Reject}
		done
	done

	for port in $U_Ports
	do
		for ip in $IPs
		do
			iptables -A INPUT -p udp --dport $port -s ${IPs} -j REJECT --reject-with ${Reject}
		done
	done
}

sleep 1
block
echo -e "\n[${BGr}+${NC}] Module Execution Successfull\n"
echo "[$(date)] Aggressive Module Execution Completed Successfully" >> wizard.log

