#!/bin/bash
#MassBlock Modules----]

BRed='\033[1;31m' # Bold Red
BGr='\033[1;32m' # Bold Green
NC='\033[0m' # No Color

echo -e "\n[${BGr}+${NC}] Loading Mass Block Module\n"
echo "[$(date)] MassBlock Module Loaded Successfully" >> wizard.log
echo 
read -p "[*] Enter the Name/Path of File Containing the List of IP's to Block: " File_name

ipset -N MassBlock iphash
if [ "${?}" -eq 0 ]
then
	echo -e "\nCreating a set named MassBlock with ipset"
	echo "[$(date) Created set MassBlock with ipset for ${File_name}]" >> wizard.log
fi


for ip in $(cat $File_name)
do
	ipset -A MassBlock $ip
done

echo -e "\n[${BGr}+${NC}] Some Common Services-|-|-Ports\n"
echo -e "${BRed}→${NC} HTTP::80"
echo -e "${BRed}→${NC} HTTPS::443"
echo -e "${BRed}→${NC} SSH::22"
echo -e "${BRed}→${NC} FTP::21"
echo -e "${BRed}→${NC} Telnet::23"
echo -e "${BRed}→${NC} DNS::53"
echo -e "${BRed}→${NC} SMTP::25"
echo -e "${BRed}→${NC} POP3::110"
echo -e "${BRed}→${NC} NTP::123"
echo -e "${BRed}→${NC} IMAP::143"
echo -e "${BRed}→${NC} SNMP::161"
echo -e "${BRed}→${NC} IRC::194"
echo -e "${BRed}→${NC} NetBIOS::139--UDP"
echo -e "${BRed}→${NC} SMB::445--UDP"

read -p "[*] Enter The Port Numbers To Block::seprate by spaces if needed[TCP]:→ " T_Ports
read -p "[*] Enter The Port Numbers To Block::seprate by spaces if needed[UDP]:→ " U_Ports
echo

block() {
	for port in  $T_Ports
	do
		iptables -A INPUT -p tcp --dport $port -m set --match-set MassBlock src -j DROP
	done

	for port in $U_Ports
	do
		iptables -A INPUT -p udp --dport $port -m set --match-set MassBlock src -j DROP
	done
}

block

echo "[$(date)] MassBlock Executed Successfully" >> wizard.log
echo -e "\n[${BGr}+${NC}] Module Execution Successfull"
sleep 1



