#!/bin/bash
#MassBlock Modules----]

BRed='\033[1;31m' # Bold Red
BGr='\033[1;32m' # Bold Green
NC='\033[0m' # No Color

echo -e "\n[${BGr}+${NC}] Loading Mass Block Module\n"
echo "[$(date)] MassBlock Module Loaded Successfully" >> wizard.log
echo 
read -p "[*] Enter the Name/Path of File Containing the List of IP's to Block: " File_name

ipset -N MassBlock iphash
if [ "${?}" -eq 0 ]
then
	echo -e "\nCreating a set named MassBlock with ipset"
	echo "[$(date) Created set MassBlock with ipset for ${File_name}]" >> wizard.log
fi


for ip in $(cat $File_name)
do
	ipset -A MassBlock $ip
done

echo "[${GR}+${NC}] Some Common Services-|-|-Ports"
echo "${BRed}→${NC} HTTP::80"
echo "${BRed}→${NC} HTTPS::443"
echo "${BRed}→${NC} SSH::22"
echo "${BRed}→${NC} FTP::21"
echo "${BRed}→${NC} Telnet::23"
echo "${BRed}→${NC} DNS::53"
echo "${BRed}→${NC} SMTP::25"
echo "${BRed}→${NC} POP3::110"
echo "${BRed}→${NC} NTP::123"
echo "${BRed}→${NC} IMAP::143"
echo "${BRed}→${NC} SNMP::161"
echo "${BRed}→${NC} IRC::194"
echo "${BRed}→${NC} NetBIOS::139--UDP"
echo "${BRed}→${NC} SMB::445--UDP"

read -p "[*] Enter The Port Numbers To Block::seprate by spaces if needed:→ " T_Ports
echo

block() {
	for port in  $T_Ports
	do
		if [ "$port" -ne "139" &&  "$port" -ne "445" ]
		then
			iptables -A INPUT -p tcp --dport $port -m set --match-set MassBlock src -j DROP
		else
			iptables -A INPUT -p udp --dport $port -m set --match-set MassBlock src -j DROP
		fi
	done
}



echo "[$(date)] MassBlock Executed Successfully"
echo -e "/n[${BGr}+${NC}] Module Execution Successfull"
sleep 1

