#!/bin/bash
#WizardBlock Module---under Advanced Firewall----wizard

BRed='\033[1;31m' #Bold Red
BGr='\033[1;32m' #Bold Green
NC='\033[0m' # No Color

echo -e "\n[${BGr}+${NC}] Loading WizardBlock Module\n"

